### ISSUE TITLE
Typing code sometimes stops working

### ISSUE THREAD

**Issue by FHof** [TUM-LRR/Jasmin#25] opened 2016-11-13 10:02 UTC
When using Jasmin, sometimes typing code is suddenly impossible: When pressing a key, the letter does not appear, l get following error message in lieu:
![jasminbug](https://cloud.githubusercontent.com/assets/23431138/20244770/82e616d8-a98e-11e6-8c84-4ea34966fa7c.png)
Maybe it's a [syntax highlighting](https://github.com/TUM-LRR/Jasmin/blob/master/src/jasmin/gui/SyntaxHighlighter.java#L162) bug.
l don't know how to reproduce this.

**Comment by meyerm** [comment] 2017-02-05 22:12
Since we never saw this happening and nobody can reproduce it, we must close this for now. If you ever encounter it again and can tell us more details, please don't hesitate to reopen.

**Closed by meyerm** 2017-02-05 22:12 UTC
Labels: invalid
